CREATE TABLE IF NOT EXISTS urls (
  id VARCHAR(8) PRIMARY KEY,
  long_url TEXT NOT NULL,
  total_clicks INTEGER DEFAULT 0,
  last_clicked TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
